---
title: "Gov 50 Final Project"
author: "Omer Mujawar"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Milestone 1 - Project Thoughts

I am interested in exploring data related to the recently shifting and increasingly important political landscape in Georgia. In the past two election cycles, Georgia has been at the forefront of the battle over national politics, a stark contrast from its recent solidly Republican past. I hope to explore, analyze, and visualize this changing political dynamic and the potential reasons behind this trends.

## Milestone 2 - Data and Proposal

*Did changing immigration trends and urbanization impact the 2020 Presidential Election results?* 

In this analysis, I plan on investigating the impact of immigration, and urbanization trends on the 2020 Presidential Election results (as compared to the 2016 Presidential Election results). I hypothesize that greater immigration and urbanization in districts led to a leftward and Democratic shift, which, in aggregate, helped the Democratic nominee Joe Biden win the presidency. Thus, in districts that experienced more immigration and urbanization between 2016 and 2020, I expect the Democratic nominee to have done better in 2020 than in 2016 since areas with more immigration/diversity and urbanization tend to favor Democratic candidates. On the other hand, in districts that experienced less immigration and urbanization (or even a reversal of these trends), I expect the Republican nominee to have done better in 2020 than in 2016, since areas with less immigration/urbanization and urbanization tend to favor Republican candidates. My sample consists of Congressional districts across the United States between 2016 and 2020 (prior to the changes due to the 2020 Census redistricting). My unit of analysis, thus, is an individual Congressional district. The explanatory variables of interest are whether the foreign-born population increased as well as urbanization increased between 2016 and 2020 (and how much). These variables are coded =1 if the foreign-born population share increased and if the urbanization index increased between 2016 and 2020 and =0 if they did not increase between 2016 and 2020. My outcome variable is the shift in vote percentage towards Democrats per district. For example, if a district had an outcome coded =3, then the voter percentage for the Democratic nominee increased by 3% in that district between 2016 and 2020. This variable is measured from Federal election results per district for the 2016 and 2020 presidential elections. If I observe greater Democratic vote percentages between 2016 and 2020 in districts with greater immigration and urbanization over those years, then this would provide support for my hypothesis. Otherwise, if I observe the same or negative Democratic vote percentages between 2016 and 2020 for these districts, then this would disprove my hypothesis.